# Generated by Django 5.0.1 on 2024-02-01 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_address_buyer_address_seller_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
